'use strict';
const vm=require('vm'),fs=require('fs'),path=require('path');
const constants=require('../src/constants');
let passed=0,failed=0;
const settings={presetMode:'1.24+',dryRun:false,terminalBlacklist:['shutdown']};
const moduleBox={exports:{}};
vm.runInNewContext(fs.readFileSync(path.resolve(__dirname,'../src/configuration.js'),'utf8'),{module:moduleBox,require:id=>id==='./utils'?{cfg:(k,d)=>settings[k]??d}:id==='./constants'?constants:id==='vscode'?{workspace:{workspaceFolders:[{uri:{fsPath:'/fixture/workspace'}}]}}:require(id.startsWith('./')?path.resolve(__dirname,'../src',id):id)});
const {getEffectiveConfig,setProjectProvider}=moduleBox.exports;
const ctx={globalState:{get:()=>['Always Allow','Run','Schedule']}};
function check(ok,label){if(ok)passed++;else{failed++;console.error(label);}}
setProjectProvider(()=>({patterns:['Dummy','Run'],blacklist:['/forbidden/'],dryRun:true}));
let config=getEffectiveConfig(ctx);
check(config.dryRun,'project dry-run forces observation');check(config.approvePatterns.includes('Dummy'),'project custom label retained');check(!config.approvePatterns.includes('Run'),'disabled applies to project and preset');
check(config.terminalBlacklist.join(',')==='shutdown,/forbidden/','project blacklist supplements global');
check(constants.DEFAULT_BLACKLIST.every(rule=>config.blacklist.includes(rule)),'authoritative blacklist includes all destructive defaults');
check(config.blacklist.includes('shutdown') && config.blacklist.includes('/forbidden/'),'authoritative blacklist includes user and project rules');
check(moduleBox.exports.withPolicyVersion(config).policyVersion===config.policyVersion,'version covers the complete authoritative snapshot');
settings.presetMode='custom';settings.approvePatterns=['Always Allow','Run','Schedule','Dummy'];
config=getEffectiveConfig(ctx);check(config.approvePatterns.join(',')==='Dummy','disabled filters custom');
settings.dryRun=true;setProjectProvider(()=>({dryRun:false}));check(getEffectiveConfig(ctx).dryRun,'project cannot weaken global dry-run');
const version=getEffectiveConfig(ctx).policyVersion;
check(version===getEffectiveConfig(ctx).policyVersion,'unchanged effective policy retains version');
settings.terminalWhitelist=['customtool status'];
check(version!==getEffectiveConfig(ctx).policyVersion,'whitelist content refreshes version');
check(getEffectiveConfig(ctx).terminalWhitelist[0]==='customtool status','literal whitelist data retained');
check(getEffectiveConfig(ctx).workspace==='/fixture/workspace','snapshot contains workspace');
const {withPolicyVersion}=moduleBox.exports;
check(withPolicyVersion({b:2,a:1}).policyVersion===withPolicyVersion({a:1,b:2}).policyVersion,'key order does not change version');
check(!getEffectiveConfig(ctx).autopilotProfile.enabled, 'existing users retain default non-autopilot behavior');
const autopilotVersion = getEffectiveConfig(ctx).policyVersion;
settings.autopilotProfile = { enabled: true, grants: [{ id: 'read', effect: 'allow', operation: 'read_file', target: '/fixture/input.txt', scope: 'once' }] };
check(getEffectiveConfig(ctx).autopilotProfile.grants[0].id === 'read', 'configured typed grants reach effective snapshot');
check(getEffectiveConfig(ctx).policyVersion !== autopilotVersion, 'autopilot changes invalidate policy version');
settings.autopilotProfile.grants[0].target = '*';
check(!getEffectiveConfig(ctx).autopilotProfile.enabled, 'malformed profile fails closed');
check(getEffectiveConfig(ctx).retryBudget.enabled === false, 'retry stays manual until configured');
settings.retryBudget = { enabled: true, maxPerConversation: 3 };
check(getEffectiveConfig(ctx).retryBudget.maxPerConversation === 3, 'valid retry budget reaches the snapshot');
settings.retryBudget = { enabled: true, maxPerConversation: 9 };
check(getEffectiveConfig(ctx).retryBudget.enabled === false, 'retry budget outside 1-8 fails closed');
console.log(`Results: ${passed} passed, ${failed} failed`);process.exitCode=failed?1:0;
