'use strict';
const baseAssert = require('assert/strict');
let checks = 0;
const assert = new Proxy(baseAssert, {
    apply(target, receiver, args) { checks++; return Reflect.apply(target, receiver, args); },
    get(target, key) { const value = target[key]; return typeof value === 'function' ? (...args) => { checks++; return value(...args); } : value; },
});
const { createJobTracker } = require('../src/job-tracker');
const { createObservabilityState } = require('../src/observability');
const { summarizePilot } = require('../src/pilot-metrics');
let ts = 0, eventId = 0;
const tracker = createJobTracker({}, { now: () => ts });
const host = (jobId, type, extra = {}) => tracker.record({ jobId, type, eventId: String(++eventId), evidence: 'host-job-lifecycle', ...extra });
assert.equal(host('unattended', 'started'), true);
host('unattended', 'intervention', { phase: 'setup' });
assert.equal(tracker.record({ jobId: 'unattended', eventId: 'click', type: 'completed', evidence: 'renderer-observation' }), false);
assert.equal(host('unattended', 'waiting', { waitReason: 'approval' }), true);
ts = 50; host('unattended', 'progress');
host('unattended', 'recovery-start');
ts = 100; tracker.record({ jobId: 'unattended', eventId: 'socket-open', type: 'progress', evidence: 'renderer-observation' });
assert.equal(tracker.snapshot().recoveriesToHostProgress, 0);
ts = 150; host('unattended', 'progress');
host('unattended', 'waiting', { waitReason: 'quota' });
ts = 250; host('unattended', 'completed', { eventId: 'completed' });
assert.equal(host('unattended', 'completed', { eventId: 'completed' }), false);
assert.equal(host('unattended', 'started'), false, 'terminal jobs cannot be replayed under the same id');
host('failed', 'started'); host('failed', 'failed');
host('unknown', 'started');
host('assisted', 'started'); host('assisted', 'intervention'); host('assisted', 'completed');
let metrics = tracker.snapshot();
assert.equal(metrics.observedJobs, 4);
assert.equal(metrics.completedJobs, 2);
assert.equal(metrics.unknownCompletionJobs, 1);
assert.equal(metrics.failedJobs, 1);
assert.equal(metrics.unattendedCompletionRate, .25, 'failed and unknown jobs remain in denominator');
assert.equal(metrics.setupInterventions, 1);
assert.equal(metrics.userInterventions, 1);
assert.equal(metrics.waits.approval.totalMs, 50);
assert.equal(metrics.waits.quota.totalMs, 100);
assert.equal(metrics.automaticRecoveryRate, 1);
assert.equal(metrics.recoveryToProgressMs.p95, 100, 'recovery ends at host progress, not socket open');
assert.equal(host('no-start', 'completed'), false);
assert.equal(host('unknown', 'progress', { sequence: 4 }), true);
assert.equal(host('unknown', 'failed', { sequence: 3 }), false, 'stale lifecycle callback rejected');
const restored = createJobTracker(tracker.exportState(), { now: () => ts });
assert.equal(restored.snapshot().unattendedCompletionRate, .25);
assert.equal(restored.record({ jobId: 'unattended', type: 'completed', eventId: 'completed', evidence: 'host-job-lifecycle' }), false);
const bounded = createJobTracker({}, { maxJobs: 1 });
assert.equal(bounded.record({ jobId: 'one', eventId: '1', type: 'started', evidence: 'host-job-lifecycle' }), true);
assert.equal(bounded.record({ jobId: 'two', eventId: '2', type: 'started', evidence: 'host-job-lifecycle' }), false);
const obs = createObservabilityState();
obs.push({ source: 'cdp', action: 'clicked', outcome: 'completed', jobId: 'click' });
assert.equal(obs.snapshot().jobMetrics.observedJobs, 0);
obs.recordJobEvent({ jobId: 'host', eventId: 's', type: 'started', evidence: 'host-job-lifecycle' });
obs.recordJobEvent({ jobId: 'host', eventId: 'c', type: 'completed', evidence: 'host-job-lifecycle' });
const roundtrip = createObservabilityState(obs.exportState());
assert.equal(roundtrip.snapshot().jobMetrics.unattendedCompletedJobs, 1);
assert.equal(summarizePilot([], {}, roundtrip.snapshot().jobMetrics).jobMetrics.completedJobs, 1);
assert.equal(createJobTracker().snapshot().unattendedCompletionRate, null, 'no evidence has no success rate');
console.log(`Results: ${checks} passed, 0 failed`);
